# Generated by Django 5.0 on 2023-12-27 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_colaborador', models.CharField(choices=[('par', 'Par'), ('impar', 'Ímpar'), ('diarista', 'Diarista')], default='diarista', max_length=8)),
                ('metro', models.BooleanField(default=False)),
                ('onibus', models.BooleanField(default=False)),
                ('intermunicipal', models.BooleanField(default=False)),
                ('trem', models.BooleanField(default=False)),
                ('bilhete_unico', models.BooleanField(default=False)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
