# Generated by Django 5.0 on 2023-12-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradores',
            options={'verbose_name': 'Colaboradores'},
        ),
    ]
