# Generated by Django 5.0 on 2023-12-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_colaboradores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradores',
            options={'verbose_name': 'Colaboradore'},
        ),
    ]
